import { motion } from "framer-motion";
import { Check, X } from "lucide-react";

const rows = [
  { label: "Decision making", trad: "Manual, by operators", us: "Autonomous, real-time AI" },
  { label: "Trip planning", trad: "Spreadsheets & instinct", us: "Optimization engine" },
  { label: "Exception handling", trad: "Phone calls & escalations", us: "Auto-triaged & resolved" },
  { label: "Vehicle inspections", trad: "Manual checklists", us: "Image-processing AI" },
  { label: "Reporting", trad: "Built by analysts", us: "Generated by the system" },
  { label: "Scaling operations", trad: "Hire more staff", us: "Add fleet, not headcount" },
  { label: "Learning over time", trad: "Static workflows", us: "Self-improving with every trip" },
];

const Compare = () => {
  return (
    <section id="compare" className="py-24 lg:py-32 relative">
      <div className="container-tight">
        <div className="max-w-2xl mx-auto text-center mb-16">
          <p className="text-xs uppercase tracking-[0.2em] text-primary mb-4">Why Fleetcodes</p>
          <h2 className="font-display font-bold text-4xl sm:text-5xl tracking-tight mb-5">
            Traditional SaaS waits for input. <br />
            <span className="text-gradient">Fleetcodes takes action.</span>
          </h2>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="glass-strong rounded-2xl overflow-hidden glow-border"
        >
          <div className="grid grid-cols-3 px-6 py-5 border-b border-border/60 text-sm">
            <div className="font-display font-semibold text-muted-foreground">Capability</div>
            <div className="font-display font-semibold text-muted-foreground flex items-center gap-2">
              <X className="w-4 h-4 text-destructive/70" /> Traditional TMS
            </div>
            <div className="font-display font-semibold text-gradient-primary flex items-center gap-2">
              <Check className="w-4 h-4 text-primary" /> Fleetcodes
            </div>
          </div>
          {rows.map((r, i) => (
            <div
              key={r.label}
              className={`grid grid-cols-3 px-6 py-5 text-sm hover:bg-primary/5 transition-colors ${
                i !== rows.length - 1 ? "border-b border-border/40" : ""
              }`}
            >
              <div className="font-medium">{r.label}</div>
              <div className="text-muted-foreground">{r.trad}</div>
              <div className="text-foreground font-medium">{r.us}</div>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default Compare;
