import React from "react";
import { motion } from "framer-motion";
import { Check, X, Zap } from "lucide-react";

const rows = [
  { label: "Decision making",    trad: "Manual, by operators",       us: "Autonomous, real-time AI",       badge: "< 200ms" },
  { label: "Trip planning",      trad: "Spreadsheets & instinct",    us: "ML optimization engine",         badge: "ML Route" },
  { label: "Exception handling", trad: "Phone calls & escalations",  us: "Auto-triaged & resolved",        badge: "0-touch"  },
  { label: "Vehicle inspections",trad: "Manual checklists",          us: "Image-processing AI",            badge: "Vision AI"},
  { label: "Reporting",          trad: "Built by analysts",          us: "Generated by the system",        badge: "Auto-PDF" },
  { label: "Scaling operations", trad: "Hire more staff",            us: "Add fleet, not headcount",       badge: "Unlimited"},
  { label: "Learning over time", trad: "Static workflows",           us: "Self-improving with every trip", badge: "ML Loop"  },
];

const Compare = () => {
  return (
    <section id="compare" className="pt-10 pb-8 lg:pt-12 lg:pb-10 relative overflow-hidden">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-primary/5 blur-[120px] pointer-events-none" />

      <div className="container-tight relative">
        {/* Heading */}
        <div className="max-w-2xl mb-10">
          <p className="text-xs uppercase tracking-[0.2em] text-primary mb-3 font-semibold">Why Fleetcodes</p>
          <h2 className="font-display font-bold text-3xl sm:text-4xl tracking-tight mb-4 text-slate-900 dark:text-white">
            Traditional SaaS waits for input. <br />
            <span className="text-gradient">Fleetcodes takes action.</span>
          </h2>
        </div>

        {/* ─── Mobile cards ─────────────────────────────────────────── */}
        <div className="block sm:hidden space-y-4">
          {rows.map((r, i) => (
            <motion.div
              key={r.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="bg-white dark:bg-[#0d1117] rounded-2xl p-5 border border-slate-200 dark:border-white/[0.08] flex flex-col gap-4"
            >
              <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-900 pb-2">
                <h3 className="font-display font-semibold text-slate-800 dark:text-slate-200 text-sm">{r.label}</h3>
                <span className="text-[9px] bg-primary/10 border border-primary/20 text-primary px-2 py-0.5 rounded-full font-mono font-bold tracking-wide">
                  {r.badge}
                </span>
              </div>
              <div className="grid grid-cols-2 gap-3 text-[11px] leading-relaxed">
                <div className="bg-rose-500/5 border border-rose-500/10 rounded-xl p-3 text-left">
                  <div className="text-[9px] text-rose-500 dark:text-rose-400 font-semibold mb-1 flex items-center gap-1 uppercase tracking-wider">
                    <X className="w-3 h-3 shrink-0" /> Traditional TMS
                  </div>
                  <div className="text-slate-500 dark:text-slate-400">{r.trad}</div>
                </div>
                <div className="bg-primary/5 border border-primary/15 rounded-xl p-3 text-left shadow-glow">
                  <div className="text-[9px] text-primary font-semibold mb-1 flex items-center gap-1 uppercase tracking-wider">
                    <Check className="w-3 h-3 shrink-0" /> Fleetcodes
                  </div>
                  <div className="text-slate-800 dark:text-slate-100 font-medium">{r.us}</div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* ─── Desktop table ─────────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="hidden sm:block rounded-2xl overflow-hidden bg-white dark:bg-[#0d1117] border border-slate-200 dark:border-white/[0.08] shadow-sm"
        >
          {/* Column header */}
          <div className="grid grid-cols-12 bg-slate-100 dark:bg-[#161b22] border-b border-slate-200 dark:border-white/[0.07]">
            {/* Capability label */}
            <div className="col-span-4 px-7 py-4 flex items-end border-r border-slate-200 dark:border-white/[0.05]">
              <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600 dark:text-[#64748b] font-semibold">
                Capability
              </span>
            </div>

            {/* Traditional TMS */}
            <div className="col-span-4 px-6 py-4 flex flex-col gap-1 border-r border-slate-200 dark:border-white/[0.05]">
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 rounded-full flex items-center justify-center bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-500/25">
                  <X className="w-3 h-3 text-rose-500" />
                </div>
                <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600 dark:text-[#6b7280] font-semibold">
                  Traditional TMS
                </span>
              </div>
            </div>

            {/* Fleetcodes — highlighted */}
            <div className="col-span-4 px-6 py-4 flex flex-col gap-1 bg-primary/5 dark:bg-primary/[0.06] border-l border-primary/20">
              <div className="flex items-center gap-2 flex-wrap">
                <div className="w-5 h-5 rounded-full flex items-center justify-center shrink-0 bg-primary/10 dark:bg-primary/20 border border-primary/30 dark:border-primary/40">
                  <Check className="w-3 h-3 text-primary" />
                </div>
                <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary font-bold">
                  Fleetcodes
                </span>
                <span className="font-mono text-[8px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full"
                  style={{ background: "var(--color-primary)", color: "white", letterSpacing: "0.12em" }}>
                  Recommended
                </span>
              </div>
            </div>
          </div>

          {/* Rows */}
          {rows.map((r, i) => {
            const isLast = i === rows.length - 1;
            return (
              <div
                key={r.label}
                className={`grid grid-cols-12 group hover:bg-slate-50 dark:hover:bg-white/[0.025] transition-colors duration-150 ${!isLast ? "border-b border-slate-100 dark:border-white/[0.05]" : ""}`}
              >
                {/* Capability */}
                <div className="col-span-4 px-7 py-4 flex items-center border-r border-slate-100 dark:border-white/[0.05]">
                  <span className="text-sm font-semibold text-slate-800 dark:text-slate-300">{r.label}</span>
                </div>

                {/* Traditional */}
                <div className="col-span-4 px-6 py-4 flex items-center gap-2.5 border-r border-slate-100 dark:border-white/[0.05]">
                  <X className="w-3.5 h-3.5 shrink-0 text-rose-400 dark:text-rose-500/40" />
                  <span className="text-sm text-slate-500 dark:text-[#64748b]">{r.trad}</span>
                </div>

                {/* Fleetcodes — highlighted column */}
                <div className="col-span-4 px-6 py-4 flex items-center justify-between gap-3 bg-primary/[0.03] dark:bg-primary/[0.04] border-l border-primary/15 dark:border-primary/[0.12]">
                  <div className="flex items-center gap-2.5">
                    <Check className="w-3.5 h-3.5 text-primary shrink-0" />
                    <span className="text-sm font-semibold text-slate-800 dark:text-[#f1f5f9]">{r.us}</span>
                  </div>
                  <span className="shrink-0 font-mono text-[10px] font-bold px-2.5 py-1 rounded tracking-wide"
                    style={{ background: "rgba(124,58,237,0.15)", border: "1px solid rgba(124,58,237,0.35)", color: "var(--color-primary)" }}>
                    {r.badge}
                  </span>
                </div>
              </div>
            );
          })}

          {/* Bottom CTA bar */}
          <div className="grid grid-cols-12 bg-slate-50 dark:bg-[#161b22] border-t border-slate-200 dark:border-white/[0.07]">
            <div className="col-span-8 px-7 py-4 flex items-center gap-2 text-slate-500 dark:text-[#4b5563]">
              <Zap className="w-3.5 h-3.5" />
              <span className="text-xs font-mono">Every row above is handled autonomously by Fleetcodes — zero manual intervention.</span>
            </div>
            <div className="col-span-4 px-6 py-4 flex items-center justify-end border-l border-primary/20 bg-primary/[0.03] dark:bg-primary/[0.06]">
              <span className="text-xs font-semibold text-primary">14-day deployment guarantee →</span>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default Compare;
